name: cpn-telegram-bot

services:
  bot:
    build: .
    restart: on-failure
    environment:
      DB_URI: mongodb://root:root@mongo:27017/
  db:
    image: 'mongo:8'
    ports:
      - 8081:8081
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
