name: cpn-telegram-bot

services:
  cpn:
    build: .
    restart: unless-stopped
    environment:
      DB_URI: 'mongodb://root:example@db:27017'
      LOCAL_BOT_API_URL: 'http://bot:8081/bot'
    develop:
      watch:
        - path: src/
          target: /app/src/
          action: sync+restart
        - path: pyproject.toml
          target: /app/pyproject.toml
          action: rebuild
    volumes:
      - .env:/app/.env
    depends_on:
      db:
        required: true
        condition: service_started
      bot:
        required: true
        condition: service_started

  bot:
    image: 'aiogram/telegram-bot-api:8.2'
    ports:
      - 8081:8081
    restart: unless-stopped
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_HTTP_PORT: 8081
      TELEGRAM_LOCAL: 1
      TELEGRAM_STAT: 1

  db:
    image: 'mongo:8'
    ports:
      - 27017:27018
    restart: unless-stopped
    volumes:
      - db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  db:
